/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mihoyo.genshinpoker;

/**
 *
 * @author 13009
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    public GamePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_topImage = new javax.swing.JPanel();
        label_topImage = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_poolWithButton = new javax.swing.JPanel();
        panel_carPool = new javax.swing.JPanel();
        panel_buttons = new javax.swing.JPanel();
        button_start = new javax.swing.JButton();
        button_out = new javax.swing.JButton();
        button_pass = new javax.swing.JButton();
        panel_playerCom1 = new javax.swing.JPanel();
        panel_playerCom2 = new javax.swing.JPanel();
        panel_player = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_topImage.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_topImage.add(label_topImage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_topImage, gridBagConstraints);

        panel_main.setLayout(new java.awt.GridBagLayout());

        panel_poolWithButton.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout panel_carPoolLayout = new javax.swing.GroupLayout(panel_carPool);
        panel_carPool.setLayout(panel_carPoolLayout);
        panel_carPoolLayout.setHorizontalGroup(
            panel_carPoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_carPoolLayout.setVerticalGroup(
            panel_carPoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_poolWithButton.add(panel_carPool, new java.awt.GridBagConstraints());

        panel_buttons.setLayout(new java.awt.GridLayout(1, 3));

        button_start.setText("jButton1");
        panel_buttons.add(button_start);

        button_out.setText("jButton1");
        panel_buttons.add(button_out);

        button_pass.setText("jButton1");
        panel_buttons.add(button_pass);

        panel_poolWithButton.add(panel_buttons, new java.awt.GridBagConstraints());

        panel_main.add(panel_poolWithButton, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout panel_playerCom1Layout = new javax.swing.GroupLayout(panel_playerCom1);
        panel_playerCom1.setLayout(panel_playerCom1Layout);
        panel_playerCom1Layout.setHorizontalGroup(
            panel_playerCom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_playerCom1Layout.setVerticalGroup(
            panel_playerCom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_main.add(panel_playerCom1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout panel_playerCom2Layout = new javax.swing.GroupLayout(panel_playerCom2);
        panel_playerCom2.setLayout(panel_playerCom2Layout);
        panel_playerCom2Layout.setHorizontalGroup(
            panel_playerCom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_playerCom2Layout.setVerticalGroup(
            panel_playerCom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_main.add(panel_playerCom2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout panel_playerLayout = new javax.swing.GroupLayout(panel_player);
        panel_player.setLayout(panel_playerLayout);
        panel_playerLayout.setHorizontalGroup(
            panel_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_playerLayout.setVerticalGroup(
            panel_playerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_main.add(panel_player, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_main, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_out;
    private javax.swing.JButton button_pass;
    private javax.swing.JButton button_start;
    private javax.swing.JLabel label_topImage;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JPanel panel_carPool;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_player;
    private javax.swing.JPanel panel_playerCom1;
    private javax.swing.JPanel panel_playerCom2;
    private javax.swing.JPanel panel_poolWithButton;
    private javax.swing.JPanel panel_topImage;
    // End of variables declaration//GEN-END:variables
}
