/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mihoyo.genshinpoker;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 * 游戏登录界面
 * @author onemotre
 * &#064;Date:  2021-10-12 20:00:00
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    public GamePage() {
        java.awt.Image imageBase = new ImageIcon(getClass().getResource("/com/mihoyo/genshinpoker/images/background/background.jpeg")).getImage();
        this.frameSizeHeight = imageBase.getHeight(null);
        this.frameSizeWidth = imageBase.getWidth(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_main = new javax.swing.JPanel();
        panel_topImage = new javax.swing.JPanel();
        label_topImage = new javax.swing.JLabel();
        panel_playerCom1 = new javax.swing.JPanel();
        panel_playerCom2 = new javax.swing.JPanel();
        panel_player = new javax.swing.JPanel();
        panel_cardPool = new javax.swing.JPanel();
        label_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //TODO: 需要改成false
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        //TODO: 需要改成false
        panel_main.setOpaque(true);
        // set the base size
        panel_main.setBounds(0, 0, this.frameSizeWidth, this.frameSizeHeight);
        panel_main.setLayout(new java.awt.BorderLayout());

        panel_topImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        javax.swing.ImageIcon iconTopFrame = new javax.swing.ImageIcon(getClass().getResource("/com/mihoyo/genshinpoker/images/background/bottomFrame.png"));
        java.awt.Image image = iconTopFrame.getImage();
        int topImageHeight = this.frameSizeWidth * image.getHeight(null) / image.getWidth(null);
        java.awt.Image newImage = image.getScaledInstance(this.frameSizeWidth, topImageHeight, java.awt.Image.SCALE_SMOOTH);
        panel_topImage.setOpaque(false);

        iconTopFrame = new javax.swing.ImageIcon(newImage);
        label_topImage.setIcon(iconTopFrame);
        label_topImage.setOpaque(false);
        panel_topImage.setBounds(0, 0, this.frameSizeWidth, topImageHeight);

        panel_main.add(panel_topImage, BorderLayout.NORTH);

        panel_playerCom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_playerCom1.setOpaque(false);
        panel_main.add(panel_playerCom1, BorderLayout.EAST);

        panel_playerCom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_playerCom2.setOpaque(false);
        panel_main.add(panel_playerCom2, BorderLayout.WEST);

        panel_player.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_player.setOpaque(false);
        panel_main.add(panel_player, BorderLayout.SOUTH);

        javax.swing.GroupLayout panel_cardPoolLayout = new javax.swing.GroupLayout(panel_cardPool);
        panel_cardPool.setLayout(panel_cardPoolLayout);
        panel_cardPool.setOpaque(false);
        panel_main.add(panel_cardPool, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.NONE;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(181, 301, 182, 302);
        getContentPane().add(panel_main, gridBagConstraints);

        javax.swing.ImageIcon iconBackGround = new javax.swing.ImageIcon(getClass().getResource("/com/mihoyo/genshinpoker/images/background/background.jpeg"));
        java.awt.Image imageBackGround = iconBackGround.getImage();
        label_background.setIcon(iconBackGround);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.NONE;
        getContentPane().add(label_background, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePage jf = new GamePage();
                jf.setBounds(0, 0, jf.frameSizeWidth, jf.frameSizeHeight);
                jf.setVisible(true);

            }
        });
//        java.awt.EventQueue.invokeLater(() -> {
//            new GamePage().setVisible(true);
//        });
        
        
    }

    private int frameSizeWidth;
    private int frameSizeHeight;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel label_topImage;
    private javax.swing.JPanel panel_cardPool;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_player;
    private javax.swing.JPanel panel_playerCom1;
    private javax.swing.JPanel panel_playerCom2;
    private javax.swing.JPanel panel_topImage;
    // End of variables declaration//GEN-END:variables
}
