package com.mihoyo.genshinpoker;
import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 *
 * @author onemotre
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    public GamePage() {
        initParam();
        initComponents();
    }

    /**
     * &#064;brief  窗体、组件大小定义，素材大小重塑
     * &#064;date  2021-10-12 20:00:00
     */
    private void initParam() {
        // 素材初始化
        this.iconTopImage = new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/com/mihoyo/genshinpoker/images/background/bottomFrame.png")));
        this.iconBackGround = new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/com/mihoyo/genshinpoker/images/background/background.jpeg")));
        this.iconCardBack = new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/com/mihoyo/genshinpoker/images/pokerCard/back.jpg")));
        this.iconButton = new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/com/mihoyo/genshinpoker/images/background/button.png")));
        this.icon = new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/com/mihoyo/genshinpoker/images/background/icon.jpg")));

        java.awt.Image imageTop;
        java.awt.Image imageBackGround;
        java.awt.Image imageCardBack;
        java.awt.Image imageButton;
        imageTop = iconTopImage.getImage();
        imageBackGround = iconBackGround.getImage();
        imageCardBack = iconCardBack.getImage();
        imageButton = iconButton.getImage();

        // 窗体、顶部图片大小
        this.sizeFrameWidth = imageBackGround.getWidth(null);
        this.sizeTopImageHeight = imageBackGround.getWidth(null) * imageTop.getHeight(null) / imageTop.getWidth(null) - 20;
        this.sizeFrameHeight = imageBackGround.getHeight(null) + imageTop.getHeight(null);

        // 牌面大小
        this.sizeCardHeight = imageCardBack.getHeight(null) / 10;
        this.sizeCardWidth = imageCardBack.getWidth(null) / 10;

        // 玩家组件大小
        this.sizePlayerHeight = this.sizeCardHeight + 4;
        this.sizePlayerWidth = this.sizeFrameWidth;

        // 按键大小
        this.sizeButtonHeight = imageButton.getHeight(null) / 5;
        this.sizeButtonWidth = imageButton.getWidth(null) / 5;

        // 电脑组件大小
        this.sizePlayerComHeight = imageBackGround.getHeight(null) - this.sizePlayerHeight;
        this.sizePlayerComWidth = this.sizeCardWidth + 6;

        // 操作区大小
        this.sizeOperatorHeight = this.sizeButtonHeight;
        this.sizeOperatorWidth = this.sizeFrameWidth;

        // 牌池大小
        this.sizeCardPoolHeight = imageBackGround.getHeight(null) - this.sizePlayerHeight - this.sizeOperatorHeight;
        this.sizeCardPoolWidth = imageBackGround.getWidth(null) - this.sizePlayerComWidth * 2;


        //////////////////////////// 素材大小重塑 ////////////////////////////
        java.awt.Image newImage;
        // 顶部图片
        newImage = imageTop.getScaledInstance(this.sizeFrameWidth, this.sizeTopImageHeight, java.awt.Image.SCALE_SMOOTH);
        this.iconTopImage.setImage(newImage);
        // 牌背面
        newImage = imageCardBack.getScaledInstance(this.sizeCardWidth, this.sizeCardHeight, java.awt.Image.SCALE_SMOOTH);
        this.iconCardBack.setImage(newImage);
        // 按钮
        newImage = imageButton.getScaledInstance(this.sizeButtonWidth, this.sizeButtonHeight, java.awt.Image.SCALE_SMOOTH);
        this.iconButton.setImage(newImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /* <editor-fold default-state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents */
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_topImage = new javax.swing.JPanel();
        panel_main = new javax.swing.JPanel();
        panel_player = new javax.swing.JPanel();
        panel_playerCom1 = new javax.swing.JPanel();
        panel_playerCom2 = new javax.swing.JPanel();
        panel_cardPool = new javax.swing.JPanel();
        panel_operateArea = new javax.swing.JPanel();
        button_start = new javax.swing.JButton();
        button_out = new javax.swing.JButton();
        button_pass = new javax.swing.JButton();
        label_topImage = new javax.swing.JLabel();
        label_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        this.setIconImage(this.icon.getImage());
        this.setTitle("GenShinPoker");

        panel_topImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_topImage.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_topImage, gridBagConstraints);

        panel_main.setLayout(new java.awt.GridBagLayout());
        panel_main.setOpaque(false);

        panel_player.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_player.setOpaque(false);
        panel_main.add(panel_player, new java.awt.GridBagConstraints());

        panel_playerCom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_playerCom1.setOpaque(false);
        panel_main.add(panel_playerCom1, new java.awt.GridBagConstraints());

        panel_playerCom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_playerCom2.setOpaque(false);
        panel_main.add(panel_playerCom2, new java.awt.GridBagConstraints());

        panel_cardPool.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_cardPool.setOpaque(false);
        panel_main.add(panel_cardPool, new java.awt.GridBagConstraints());

        panel_operateArea.setLayout(new java.awt.GridBagLayout());
        panel_operateArea.setOpaque(false);


        button_start.setIcon(this.iconButton);
        button_start.setText("开始游戏");
        button_start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_start.setVerticalTextPosition(SwingConstants.CENTER);
        button_start.setBorderPainted(false);
        button_start.setContentAreaFilled(false);
        button_start.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = this.sizeFrameWidth;
        gridBagConstraints.weighty = this.sizeFrameHeight;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_operateArea.add(button_start, gridBagConstraints);

        button_out.setIcon(this.iconButton);
        button_out.setText("出牌");
        button_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_out.setVerticalTextPosition(SwingConstants.CENTER);
        button_out.setBorderPainted(false);
        button_out.setContentAreaFilled(false);
        button_out.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = this.sizeFrameWidth;
        gridBagConstraints.weighty = this.sizeFrameHeight;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_operateArea.add(button_out, gridBagConstraints);

        button_pass.setIcon(this.iconButton);
        button_pass.setText("不出");
        button_pass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_pass.setVerticalTextPosition(SwingConstants.CENTER);
        button_pass.setBorderPainted(false);
        button_pass.setContentAreaFilled(false);
        button_pass.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = this.sizeFrameWidth;
        gridBagConstraints.weighty = this.sizeFrameHeight;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_operateArea.add(button_pass, gridBagConstraints);

        panel_main.add(panel_operateArea, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_main, gridBagConstraints);

        label_topImage.setIcon(this.iconTopImage);
        label_topImage.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(label_topImage, gridBagConstraints);

        label_background.setIcon(this.iconBackGround);
        label_background.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(label_background, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold default-state="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
    }

    ////////////////////////// 窗体大小定义 //////////////////////////
    private int sizeTopImageHeight;  // 顶部图片高度
    private int sizeFrameWidth;  // 窗体宽度
    private int sizeFrameHeight; // 窗体高度
    private int sizeCardPoolWidth;   // 牌池宽度
    private int sizeCardPoolHeight;  // 牌池高度
    private int sizeOperatorWidth;   // 操作区宽度
    private int sizeOperatorHeight;  // 操作区高度
    private int sizeCardWidth;   // 牌宽度
    private int sizeCardHeight;  // 牌高度
    private int sizePlayerComWidth;  // 玩家组件宽度
    private int sizePlayerComHeight;  // 玩家组件高度
    private int sizeButtonWidth; // 按钮宽度
    private int sizeButtonHeight;    // 按钮高度
    private int sizePlayerWidth; // 玩家宽度
    private int sizePlayerHeight;    // 玩家高度

    ////////////////////////// 素材定义 //////////////////////////
    private javax.swing.ImageIcon iconTopImage; // 顶部图片
    private javax.swing.ImageIcon iconBackGround; // 背景图片
    private javax.swing.ImageIcon iconCardBack; // 牌背面
    private javax.swing.ImageIcon iconButton; // 按钮
    private javax.swing.ImageIcon icon;

    ////////////////////////// 组件 //////////////////////////
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_out;
    private javax.swing.JButton button_pass;
    private javax.swing.JButton button_start;
    private javax.swing.JLabel label_background;
    private javax.swing.JLabel label_topImage;
    private javax.swing.JPanel panel_cardPool;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_operateArea;
    private javax.swing.JPanel panel_player;
    private javax.swing.JPanel panel_playerCom1;
    private javax.swing.JPanel panel_playerCom2;
    private javax.swing.JPanel panel_topImage;
    // End of variables declaration//GEN-END:variables
}
